server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ? CRITICAL for Supabase pooler
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.com.notesnap=DEBUG
logging.level.org.springframework.web=INFO

notepad.character.limit=50000
notepad.expiry.days=10